title: "Corporate Analysis"
description: "We are blogging on Corporate Finance Theory and Real Analysis"
theme: minima

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
# Adding categories
collections:
  categories:
    output: true
    permalink: /:collection/:categories:output_ext


