title: "Corporate Analysis"
description: "Blogging on Corporate Finance and Analysis"
theme: minima

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge


